ifneq (,$(wildcard /sbin/apk))
.PHONY : deps
## Install all dependencies for alpine
deps::
	mkdir -p $(GOBIN)
	apk add --update go
	@curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
endif

