version: '1.0'

stages:
- Prepare
- Test

steps:
  main_clone:
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Initialize"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: CF-default
    revision: ${{CF_REVISION}}

  test:
    type: "parallel"
    test_module:
      title: Test module
      image: ${{TEST_IMAGE}}
      stage: Test
      commands:
      - make -C test/ module

    test_examples_complete:
      title: Test "examples/complete"
      image: ${{TEST_IMAGE}}
      stage: Test
      commands:
      - make -C test/ examples/complete
